version: "3"
services:
  web:
    build: .
    volumes:
      - .:/code
      - ./fixtures:/fixtures
    command: bash -c "python manage.py flush --noinput && python manage.py migrate && python manage.py remove_expired_links && \
      python manage.py loaddata thumbnail_size_fixture.json && python manage.py \
      loaddata account_tier_fixture.json && python manage.py add_admin && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"