# Generated by Django 4.2.5 on 2023-09-15 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_original_file_link', models.BooleanField(default=False)),
                ('is_expiring_link', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountTier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounttier')),
            ],
        ),
        migrations.AddField(
            model_name='accounttier',
            name='thumbnailSizes',
            field=models.ManyToManyField(to='accounts.thumbnailsize'),
        ),
    ]
