# Generated by Django 4.2.5 on 2023-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttier_thumbnail_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='rfeef', max_length=255),
            preserve_default=False,
        ),
    ]
