# Generated by Django 4.2.5 on 2023-09-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='account_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounttier'),
        ),
    ]
