# Generated by Django 4.2.5 on 2023-09-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_useraccount_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
