"""
Django settings for file_uploader project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x(!3&5a*10-c66)p&#%%#qpwik2ron-=_i9-egpb^y&t#fak)1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'accounts.apps.AccountsConfig',
    'images.apps.ImagesConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'allauth',
    'allauth.account',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'file_uploader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'file_uploader.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Image uploading

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Validation constants

DEFAULT_EXPIRATION_TIME_SEC = 300
MIN_EXPIRATION_TIME_SEC = 300
MAX_EXPIRATION_TIME_SEC = 30000
VALID_IMAGE_FORMATS = ['.png', '.jpg', '.jpeg']


# Login authentication configuration

ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = True
AUTH_USER_MODEL = 'accounts.UserAccount'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

SITE_ID = 1
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'file-uploader-auth'

# Dropbox storage configuration

DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'

DROPBOX_APP_KEY = 'g1fobrr6zo3uh0k'
DROPBOX_APP_SECRET = 'i1lu2041q42tp9u'
# sl.BmUyamWVNS1JZAs9UMDbO9aFcIN8kaWtUjKW8lmrKCGLlZlM4iHtc3FIKLqSD6rl-aKy5aJu7FRGPTiXK1bHPzujShkpjfv3MDqvcOTdeIHI0CoWA1C1XHPGjUz_pCcwuGa7HAo8KeWULuxdN9pOzIk
DROPBOX_ACCESS_TOKEN = "sl.BmWjKEWha7ZfqzbH7sRodqCc5ik3VOzKMRJ9887KWsP7-XhcN__Et2enNF6bm9FM6__cPAtOqjg4bQMpVuQ0P4NoMQKFcZpdCq_XtB0_muvZGPCOBKe90m5o92jjNTslTz1tN2XCbZ7ddUfxQfQpuu0"
# DROPBOX_OAUTH2_TOKEN = 'sl.BmVH_C0Di0f4xZyc9jZ4TzOtvA2BcpMNZqb_SDHqiDvBThU74eQomqiPoCyScGcHVBIm07oN8EooZ_ustcrD-CGJZ1AscLmT4hX-N1PVa5ZaTRyNMC-uc4sQmkcwkqanYwXlOJT4AGIGdVM'
DROPBOX_OAUTH2_REFRESH_TOKEN = "YTt2-12EWPgAAAAAAAAAAZFJf_awvWHV2pU24I5IzWl0O7iLYauSGI4z61Z8FNrI"
DROPBOX_API_BASE_URL = 'https://content.dropboxapi.com/2/'
DROPBOX_TIMEOUT = 50

# Redis caching
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

CACHE_TTL = 60 * 2
