# Generated by Django 4.2.5 on 2023-09-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import images.models
import images.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=images.models.upload_to, validators=[images.validators.validate_image_format])),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=None, max_length=255)),
                ('expiration_time_sec', models.IntegerField(validators=[images.validators.validate_expiration_time_sec])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
