# Generated by Django 4.2.5 on 2023-09-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expiration_time_sec',
            field=models.IntegerField(),
        ),
    ]
