# Generated by Django 4.2.5 on 2023-09-17 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_expiringlink_expiration_time_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expiringlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
